# Configuration
API_URL="http://localhost:4000"
USER_EMAIL="seed_test@example.com"
USER_PASS="password123"
USER_NAME="Seeder"

echo "🌱 Starting database seeding..."

# 1. Signup (or Login if exists) to get Token
# We try to signup first.
RESPONSE=$(curl -s -X POST "$API_URL/auth/signup" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"$USER_EMAIL\", \"password\":\"$USER_PASS\", \"username\":\"$USER_NAME\"}")

# Extract token using grep/sed (works without jq)
TOKEN=$(echo $RESPONSE | grep -o '"token":"[^"]*"' | sed 's/"token":"//;s/"//')

# If signup failed (likely user exists), try login
if [ -z "$TOKEN" ]; then
  echo "User might already exist. Logging in..."
  RESPONSE=$(curl -s -X POST "$API_URL/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$USER_EMAIL\", \"password\":\"$USER_PASS\"}")
  TOKEN=$(echo $RESPONSE | grep -o '"token":"[^"]*"' | sed 's/"token":"//;s/"//')
fi

# Check if we have a token
if [ -z "$TOKEN" ]; then
  echo "❌ Failed to authenticate. Response: $RESPONSE"
  exit 1
fi

echo "✅ Authenticated as $USER_NAME"

# 2. Create 10 Tasks
categories=("School" "Work" "Hobby" "Health" "Finance")
priorities=("low" "medium" "high" "critical")

for i in {1..10}
do
   # Pick random category and priority
   CAT=${categories[$((RANDOM % ${#categories[@]}))]}
   PRI=${priorities[$((RANDOM % ${#priorities[@]}))]}
   
   echo "Creating task $i: [$CAT] Task $i ($PRI)..."
   
   curl -s -X POST "$API_URL/tasks" \
     -H "Authorization: Bearer $TOKEN" \
     -H "Content-Type: application/json" \
     -d "{
       \"title\": \"Auto-generated Task $i\",
       \"description\": \"This is a test task generated by the seed script.\",
       \"category\": \"$CAT\",
       \"priority\": \"$PRI\"
     }" > /dev/null
done

echo "🎉 Success! 10 tasks created."